### ISSUE TITLE
vmware controller: default dynamic load balancer does not work 

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#177]
[Version]
V16.0 Fix 6
[Date]
2016/06/26

[Test category] 
Creative

[Description]
Installed VMware controller out of box. Added some bogus information into the controller app, re- selected the Host Balancing Setting to: Distribute VMs equally over all hosts (dynamically)
left the settings  'Target host name' and 'Target storage name' empty 
provisioned an instance:
ERROR CreateActions createVM Failed to create VM of instance 1467710014872
org.oscm.app.v1_0.exceptions.APPlatformException: Out of storage

[Steps to reproduce]
see above
[Expected result]
Instance provisioned
[Observed result] 
Error
[Details]
See above; 

[Messages and logs]

[2016-07-05 11:13:34] [http-thread-pool-28881(2)] INFO  VMController createInstance createInstance(InstanceID: 1467710014872 | OrganizationID: da530744 | SubscriptionID: VMware_Original_With_ALL | RequestingUser: Julia@DarkSide.com)
[2016-07-05 11:13:36] [__ejb-thread-pool11] DEBUG VMController getInstanceStatus InstanceID: 1467710014872 | OrganizationID: da530744 | SubscriptionID: VMware_Original_With_ALL
[2016-07-05 11:13:36] [__ejb-thread-pool11] DEBUG StateMachine loadStateMachine filename: create_vm.xml
[2016-07-05 11:13:36] [__ejb-thread-pool11] INFO  States invokeAction Invoking action 'createInstanceName' of state 'BEGIN' for instance '1467710014872'
[2016-07-05 11:13:36] [__ejb-thread-pool11] DEBUG DataAccessService getVCenterIdentifier vcenter: estvcenterdev1
[2016-07-05 11:13:36] [__ejb-thread-pool11] DEBUG DataAccessService getNextSequenceNumber vcenterId: 1
[2016-07-05 11:13:36] [__ejb-thread-pool11] DEBUG StateMachine getNextState Transition from current state 'BEGIN' with event 'success' into state 'CREATE_VM'
[2016-07-05 11:13:49] [__ejb-thread-pool6] DEBUG VMController getInstanceStatus InstanceID: 1467710014872 | OrganizationID: da530744 | SubscriptionID: VMware_Original_With_ALL
[2016-07-05 11:13:49] [__ejb-thread-pool6] DEBUG StateMachine loadStateMachine filename: create_vm.xml
[2016-07-05 11:13:49] [__ejb-thread-pool6] INFO  States invokeAction Invoking action 'createVM' of state 'CREATE_VM' for instance '1467710014872'
[2016-07-05 11:13:50] [__ejb-thread-pool6] DEBUG VMwareClient isConnected vSphere connection is alive. Check took 621ms. URL: https://estvcenterdev1.intern.est.fujitsu.com/sdk/vimService?wsdl, UserId: FEST\estbuild
[2016-07-05 11:13:51] [__ejb-thread-pool6] INFO  Template cloneVM cloneVMFromTemplate() template: centos52-template-wismar
[2016-07-05 11:13:51] [__ejb-thread-pool6] DEBUG Template cloneVM Datacenter: bespoc Cluster: esscluster Template: centos52-template-wismar
[2016-07-05 11:13:52] [__ejb-thread-pool6] DEBUG DiskManager getVMSystemDisk Found system disk in VM centos52-template-wismar  label: Hard disk 1 type: null summary: 15,728,640 KB
[2016-07-05 11:13:52] [__ejb-thread-pool6] DEBUG Template cloneVM Requested disk space: 4.194304E7Template disk space: 15728640 template: centos52-template-wismar
[2016-07-05 11:13:52] [__ejb-thread-pool6] DEBUG Template setHostAndStorage datacenter: bespoc cluster: esscluster
[2016-07-05 11:13:52] [__ejb-thread-pool6] DEBUG DataAccessService getHostLoadBalancerConfig vcenter: estvcenterdev1 datacenter: bespoc cluster: esscluster
[2016-07-05 11:13:52] [__ejb-thread-pool6] DEBUG Template setHostAndStorage target host not set. get host and storage from loadbalancer
[2016-07-05 11:13:52] [__ejb-thread-pool6] DEBUG Template readDatacenterInventory datacenter: bespoc cluster: esscluster
[2016-07-05 11:13:53] [__ejb-thread-pool6] DEBUG Template readDatacenterInventory addHostSystem host: estvmwdev2.intern.est.fujitsu.com
[2016-07-05 11:13:55] [__ejb-thread-pool6] DEBUG Template readDatacenterInventory addStorage host: estvmwdev2.intern.est.fujitsu.com storage: VMdev0
[2016-07-05 11:13:56] [__ejb-thread-pool6] DEBUG Template readDatacenterInventory addStorage host: estvmwdev2.intern.est.fujitsu.com storage: VMdev1
[2016-07-05 11:13:57] [__ejb-thread-pool6] DEBUG Template readDatacenterInventory addStorage host: estvmwdev2.intern.est.fujitsu.com storage: VMdev2
[2016-07-05 11:13:59] [__ejb-thread-pool6] DEBUG Template readDatacenterInventory addHostSystem host: estvmwdev1.intern.est.fujitsu.com
[2016-07-05 11:14:01] [__ejb-thread-pool6] DEBUG Template readDatacenterInventory addStorage host: estvmwdev1.intern.est.fujitsu.com storage: VMdev0
[2016-07-05 11:14:01] [__ejb-thread-pool6] DEBUG Template readDatacenterInventory addStorage host: estvmwdev1.intern.est.fujitsu.com storage: VMdev1
[2016-07-05 11:14:02] [__ejb-thread-pool6] DEBUG Template readDatacenterInventory addStorage host: estvmwdev1.intern.est.fujitsu.com storage: VMdev2
[2016-07-05 11:14:04] [__ejb-thread-pool6] DEBUG EquipartitionStorageBalancer next Ignoring invalid storage VMdev1 [Cap:299.75GB|Used:87.07GB|Level:29.05%|Limit:0.1GB]
[2016-07-05 11:14:04] [__ejb-thread-pool6] ERROR CreateActions createVM Failed to create VM of instance 1467710014872
org.oscm.app.v1_0.exceptions.APPlatformException: Out of storage
	at org.oscm.app.vmware.business.balancer.EquipartitionStorageBalancer.next(EquipartitionStorageBalancer.java:52)
	at org.oscm.app.vmware.business.balancer.StorageBalancer.next(StorageBalancer.java:1)
	at org.oscm.app.vmware.business.model.VMwareHost.getNextStorage(VMwareHost.java:58)
	at org.oscm.app.vmware.business.Template.setHostAndStorage(Template.java:453)
	at org.oscm.app.vmware.business.Template.cloneVM(Template.java:137)
	at org.oscm.app.vmware.business.statemachine.CreateActions.createVM(CreateActions.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.oscm.app.vmware.business.statemachine.States.invokeAction(States.java:74)
	at org.oscm.app.vmware.business.statemachine.StateMachine.executeAction(StateMachine.java:93)
	at org.oscm.app.vmware.service.VMController.getInstanceStatus(VMController.java:177)
	at sun.reflect.GeneratedMethodAccessor419.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1052)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1124)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:5388)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:619)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:571)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:49)
	at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:861)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:571)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doAround(SystemInterceptorProxy.java:162)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:144)
	at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:861)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:370)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:5360)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:5348)
	at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:206)
	at com.sun.ejb.containers.EJBObjectInvocationHandlerDelegate.invoke(EJBObjectInvocationHandlerDelegate.java:79)
	at com.sun.proxy.$Proxy354.getInstanceStatus(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor418.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie.dispatchToMethod(ReflectiveTie.java:144)
	at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie._invoke(ReflectiveTie.java:174)
	at com.sun.corba.ee.impl.protocol.CorbaServerRequestDispatcherImpl.dispatchToServant(CorbaServerRequestDispatcherImpl.java:528)
	at com.sun.corba.ee.impl.protocol.CorbaServerRequestDispatcherImpl.dispatch(CorbaServerRequestDispatcherImpl.java:199)
	at com.sun.corba.ee.impl.protocol.CorbaMessageMediatorImpl.handleRequestRequest(CorbaMessageMediatorImpl.java:1624)
	at com.sun.corba.ee.impl.protocol.SharedCDRClientRequestDispatcherImpl.marshalingComplete(SharedCDRClientRequestDispatcherImpl.java:126)
	at com.sun.corba.ee.impl.protocol.CorbaClientDelegateImpl.invoke(CorbaClientDelegateImpl.java:273)
	at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.privateInvoke(StubInvocationHandlerImpl.java:200)
	at com.sun.corba.ee.impl.presentation.rmi.StubInvocationHandlerImpl.invoke(StubInvocationHandlerImpl.java:152)
	at com.sun.corba.ee.impl.presentation.rmi.codegen.CodegenStubBase.invoke(CodegenStubBase.java:227)
	at org.oscm.app.v1_0.intf.__APPlatformController_Remote_DynamicStub.getInstanceStatus(org/oscm/app/v1_0/intf/__APPlatformController_Remote_DynamicStub.java)
	at org.oscm.app.v1_0.intf._APPlatformController_Wrapper.getInstanceStatus(org/oscm/app/v1_0/intf/_APPlatformController_Wrapper.java)
	at org.oscm.app.adapter.APPlatformControllerAdapter.getInstanceStatus(APPlatformControllerAdapter.java:67)
	at org.oscm.app.v1_0.service.APPTimerServiceBean.doHandleControllerProvisioning(APPTimerServiceBean.java:262)
	at org.oscm.app.v1_0.service.APPTimerServiceBean.doHandleSystems(APPTimerServiceBean.java:244)
	at org.oscm.app.v1_0.service.APPTimerServiceBean.handleTimer(APPTimerServiceBean.java:180)
	at sun.reflect.GeneratedMethodAccessor415.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1052)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1124)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:5388)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:619)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:571)
	at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:49)
	at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:861)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:571)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doAround(SystemInterceptorProxy.java:162)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundTimeout(SystemInterceptorProxy.java:149)
	at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:861)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:800)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:370)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:5360)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:5348)
	at com.sun.ejb.containers.BaseContainer.callEJBTimeout(BaseContainer.java:4058)
	at com.sun.ejb.containers.EJBTimerService.deliverTimeout(EJBTimerService.java:1832)
	at com.sun.ejb.containers.EJBTimerService.access$100(EJBTimerService.java:108)
	at com.sun.ejb.containers.EJBTimerService$TaskExpiredWork.run(EJBTimerService.java:2646)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
[2016-07-05 11:14:04] [__ejb-thread-pool6] DEBUG StateMachine getNextState Transition from current state 'CREATE_VM' with event 'failed' into state 'ERROR'

**Comment by StavrevaS** [comment]
As discussed with product management, the feature with different load balancing models is not used by any customer and not required.
The UI is adapted to support only configuration of API settings for the vCenter, and the load balancing of provisioned VMs is done dinamicaly on vSphere.
If some customer needs another model of load balancing a new contribution or feature requirement should be created.

**Comment by elfriedegoetz** [comment]
Ok withMaster  2016/07/22 
tested
Distribute VMs equally over all hosts (dynamically)
left the settings 'Target host name' and 'Target storage name' empty
