### ISSUE TITLE
"VMWare controller:" error 500 when session time out occurs

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#185]
[Version]
V16.0 Fix 6
[Date]
2016/06/26

[Test category] 
Creative

[Description]
System installed in SAML mode.
Logged on to VMware Controller : https://time.darkside.com:28881/oscm-app-vmware/
Let the screen sitting for some time (30 min) till - apparently -  the session times out.
Do any action: Error 500 (see below)
When pressing the Back button or the refresh button the Authentication mask appears. 
Any logon will be rejected with error invalid user or password.

[Steps to reproduce]
see above
[Expected result]
Either logon mask and log on works or automatic renewal of token and automated log on 
[Observed result] 
The following error occurred during the last operation:
Status Code: 500
[Details]
See above; 

[Messages and logs]
error message on screen:
APP VMware Controller Configuration
The following error occurred during the last operation:

Status Code: 500
Request-URI: /oscm-app-vmware/default.jsf
Servlet name: Faces Servlet
Exception: com.sun.faces.context.FacesFileNotFoundException: /default.xhtml Not Found in ExternalContext as a Resource

app server.log:
[#|2016-07-06T12:45:41.827+0200|INFO|glassfish3.1.2|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=150;_ThreadName=Thread-2;|2016-07-06 12:45:41,827 [http-thread-pool-28881(2)] - DEBUG - Retrieving configuration settings for controller 'ess.vmware'
|#]

[#|2016-07-06T12:45:41.848+0200|SEVERE|glassfish3.1.2|javax.enterprise.resource.webcontainer.jsf.context|_ThreadID=150;_ThreadName=Thread-2;|javax.faces.application.ViewExpiredException: viewId:/balancer.xhtml - View /balancer.xhtml could not be restored.
	at com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:205)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:116)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1550)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:343)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:217)
	at org.oscm.app.vmware.ui.filter.AuthorizationFilter.doFilter(AuthorizationFilter.java:100)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:217)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:279)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:655)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:595)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:161)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:331)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:231)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$AdapterCallable.call(ContainerMapper.java:317)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:195)
	at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:860)
	at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:757)
	at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1056)
	at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:229)
	at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
	at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
	at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
	at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
	at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)
	at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)
	at com.sun.grizzly.ContextTask.run(ContextTask.java:71)
	at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:532)
	at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:513)
	at java.lang.Thread.run(Thread.java:744)
|#]

**Comment by GoebelL** [comment]
"Let the screen sitting for some time (30 min) till - apparently - the session times out."
Timeouts must not occur in active browser sessions. Sessions should first time out when the clients are terminated. In my understanding same session keep-alive mechanism as we have in the administration and marketplace portals could be reused here as well. Please check.

**Comment by grubskim** [comment]
[Details of fix] 
I have ported the current keepAlive solution we have in portal to the vmware ui. It sends the poll request to the server in intervals of session timeout from web.xml minus one minute.
