### ISSUE TITLE
The authorized organization cannot log in to the "closed" marketplace with SAML_SP mode.

### ISSUE THREAD

**Issue by jiangweiyi** [servicecatalog/development#194]
Date: 2016/07/01 
[Test category]: creative Test

Severity: major

[Steps to reproduce]
1. Log in as platform operator, create a marketplace "mp_pl".
2. Go to "manage access" page, select the above marketplace "mp_pl", check the "Authorized customers only", then select all the organizations in the list, click on "save" button, to make all the organizations have access to this marketplace.
3. Go to the "mp_pl" marketplace page, log in as one of the selected organizations.

[Expected result]
Log in successfully.

[Observed result]
With INTERNAL mode, log in successfully.
With SAML_SP mode, log in failed with the message "The operation failed".

[Details]
I tried the same steps in CTMG with both INTERNAL and SAML_SP mode, with INTERNAL mode is OK, but  with SAML_SP mode failed, so strange, is there any other additional settings with SAML_SP mode?

**Comment by GoebelL** [comment]
>With SAML_SP mode, log in failed with the message "The operation failed".

There should be a respective entry in the log file of the resp. Glassfish domain, server.log. Could you attach this section please.

**Comment by GoebelL** [comment]
From @AndreasTWolf 

[#|2016-07-07T15:14:31.438+0200|SEVERE|glassfish3.1.2|javax.enterprise.resource.webcontainer.jsf.context|_ThreadID=239;_ThreadName=Thread-2;|org.jboss.weld.context.NonexistentConversationException: WELD-000321 No conversation found to restore for id 5
	at org.jboss.weld.context.AbstractConversationContext.activate(AbstractConversationContext.java:221)
	at org.jboss.weld.jsf.WeldPhaseListener.activateConversations(WeldPhaseListener.java:108)
	at org.jboss.weld.jsf.WeldPhaseListener.beforePhase(WeldPhaseListener.java:85)
	at com.sun.faces.lifecycle.Phase.handleBeforePhase(Phase.java:228)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:99)
	at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:116)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1550)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:343)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:217)
	at org.oscm.ui.filter.AuthorizationFilter.proceedWithFilterChain(AuthorizationFilter.java:262)
	at org.oscm.ui.filter.AuthorizationFilter.doFilter(AuthorizationFilter.java:126)

**Comment by jiangweiyi** [comment]
There are only some logs in system.log at the time login failed,  no other logs in server.log

In system.log file:
07/08/2016_09:40:56.764 FSP_INTS-BSS: ERROR: ThreadID http-thread-pool-8080(1): ExceptionActionListener: ?? key 'ERROR' not found ??
javax.faces.FacesException: #{bean[action]}: java.lang.NullPointerException
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:117)
	at org.oscm.ui.common.ExceptionActionListener.processAction(ExceptionActionListener.java:41)
	at org.omnifaces.eventlistener.ResetInputAjaxActionListener.processAction(ResetInputAjaxActionListener.java:197)
	at javax.faces.component.UICommand.broadcast(UICommand.java:315)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:786)
	at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1251)
	at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1550)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:343)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:217)
	at org.oscm.ui.filter.AuthorizationFilter.proceedWithFilterChain(AuthorizationFilter.java:262)
	at org.oscm.ui.filter.AuthorizationFilter.doFilter(AuthorizationFilter.java:126)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:217)
	at org.oscm.ui.filter.NonexistentConversationFilter.doFilter(NonexistentConversationFilter.java:37)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:217)
	at org.oscm.ui.filter.MarketplaceContextFilter.doFilter(MarketplaceContextFilter.java:116)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:217)
	at org.apache.catalina.core.ApplicationDispatcher.doInvoke(ApplicationDispatcher.java:807)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:671)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:505)
	at org.apache.catalina.core.ApplicationDispatcher.doDispatch(ApplicationDispatcher.java:476)
	at org.apache.catalina.core.ApplicationDispatcher.dispatch(ApplicationDispatcher.java:355)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:305)
	at org.oscm.ui.filter.RequestRedirector.forward(RequestRedirector.java:45)
	at org.oscm.ui.filter.ClosedMarketplaceFilter.doFilter(ClosedMarketplaceFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:217)
	at org.oscm.ui.filter.IdPResponseFilter.doFilter(IdPResponseFilter.java:146)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:217)
	at org.oscm.ui.filter.HttpMethodFilter.doFilter(HttpMethodFilter.java:69)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:217)
	at org.oscm.ui.filter.DisableUrlSessionFilter.doFilter(DisableUrlSessionFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:256)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:217)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:279)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:655)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:595)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:161)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:331)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:231)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$AdapterCallable.call(ContainerMapper.java:317)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:195)
	at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:860)
	at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:757)
	at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1056)
	at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:229)
	at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
	at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
	at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
	at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
	at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)
	at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)
	at com.sun.grizzly.ContextTask.run(ContextTask.java:71)
	at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:532)
	at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:513)
	at java.lang.Thread.run(Thread.java:722)
Caused by: javax.faces.el.EvaluationException: java.lang.NullPointerException
	at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:101)
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:101)
	... 64 more
Caused by: java.lang.NullPointerException
	at org.oscm.ui.beans.UserBean.login(UserBean.java:454)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.sun.el.parser.AstValue.invoke(AstValue.java:254)
	at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:302)
	at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:39)
	at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
	at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87)
	... 65 more

**Comment by grubskim** [comment]
Issue was caused by the lack of SAML handling in the new ClosedMarketplaceFilter. Added redirection to the error page when user tries to access restricted marketplace, to which they don't have access, in SAML mode, after login. The cases where user is already logged in and tries to access restricted marketplace still need to be handled. Right now it shows the marketplace with the error message, it should show the same page as after login.

**Comment by jiangweiyi** [comment]
Verified by FNST
[Verified-build]BES_MASTER_DELIVERY-744 2016/07/22
[Verified-details]With SAML_SP mode, if the organization has access to the marketplace, he can log in successfully, if has no, he will log in failed with the message "Login failed. You have no access to this marketplace. " So verified.

**Comment by SuessI** [comment]
Required help pages are now available in master branch.
- error_loginToClosedMarketplace.htm
- error_accessToClosedMarketplace.htm

**Comment by grubskim** [comment]
Details of fix:

ClosedMarketplaceFilter now differenciates between SAML_SP and INTERNAL modes. In SAML case, each time user tries to access the restricted marketplace to which they do not have access, error page is displayed. 

Automatic login pop-up is not displayed in SAML mode, instead there is a redirection to the IDP login page. In case of login attempt to the restricted MP without access to it, error page is displayed, but there is no login exception and user is still logged in. This allows to go to a different MP without additional login. Error page does not have "Logout" link. In case user closes down the browser, standard 8 minute session timeout applies, after which the portal session is invalidated and deleted from the database.
