### ISSUE TITLE
Issue- while accessing https://fcp-8224d:8881/ProvisioningService/AsynchronousProvisioningProxy?wsdl

### ISSUE THREAD

**Issue by pujarisat** [servicecatalog/development#341]
Hi Team,
I have configure the OSCM development environment on my local system and I am trying to access the https://fcp-8224d:8881/ProvisioningService/AsynchronousProvisioningProxy?wsdl service. I am getting below error 
Error: 
 Invalid wsdl request https://fcp-18224d:8881/ProvisioningService/AsynchronousProvisioningProxy

Could you please Help or suggest me 
![image](https://cloud.githubusercontent.com/assets/22190140/18902220/21591480-856f-11e6-9d3f-c6076dca74de.png)

-
Thanks
Satling

**Comment by DawidCh** [comment]
Hi.
Do you have any logs in bes domain? Check in glassfish admin console if the endpoint with name ProvisioningService is deployed in container withing the oscm application.
Regards, D.

**Comment by pujarisat** [comment]
Hi @DawidCh 

below error geting in app server log file
java.lang.UnsupportedClassVersionError: UnsupportedClassVersionError: Class org.oscm.provisioning.intf.jaxws.CreateInstance has unsupported major or minor version numbers, which are greater than those found in the Java Runtime Environment version 1.7.0_45
	at com.sun.enterprise.loader.ASURLClassLoader.findClass(ASURLClassLoader.java:759)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.sun.xml.ws.model.RuntimeModeler.getRequestWrapperClass(RuntimeModeler.java:360)
	at com.sun.xml.ws.model.RuntimeModeler.processDocWrappedMethod(RuntimeModeler.java:780)
	at com.sun.xml.ws.model.RuntimeModeler.processMethod(RuntimeModeler.java:711)
	at com.sun.xml.ws.model.RuntimeModeler.processClass(RuntimeModeler.java:472)
	at com.sun.xml.ws.model.RuntimeModeler.buildRuntimeModel(RuntimeModeler.java:314)
	at com.sun.xml.ws.db.DatabindingImpl.<init>(DatabindingImpl.java:99)
	at com.sun.xml.ws.db.DatabindingProviderImpl.create(DatabindingProviderImpl.java:74)
	at com.sun.xml.ws.db.DatabindingProviderImpl.create(DatabindingProviderImpl.java:58)
	at com.sun.xml.ws.db.DatabindingFactoryImpl.createRuntime(DatabindingFactoryImpl.java:130)
	at com.sun.xml.ws.server.EndpointFactory.createSEIModel(EndpointFactory.java:433)
	at com.sun.xml.ws.server.EndpointFactory.create(EndpointFactory.java:268)
	at com.sun.xml.ws.server.EndpointFactory.createEndpoint(EndpointFactory.java:145)
	at com.sun.xml.ws.api.server.WSEndpoint.create(WSEndpoint.java:569)
	at com.sun.xml.ws.api.server.WSEndpoint.create(WSEndpoint.java:552)
	at com.sun.xml.ws.api.server.WSEndpoint.create(WSEndpoint.java:623)
	at org.glassfish.webservices.EjbRuntimeEndpointInfo.prepareInvocation(EjbRuntimeEndpointInfo.java:271)
	at org.glassfish.webservices.Ejb3MessageDispatcher.handleGet(Ejb3MessageDispatcher.java:150)
	at org.glassfish.webservices.Ejb3MessageDispatcher.invoke(Ejb3MessageDispatcher.java:93)
	at org.glassfish.webservices.EjbWebServiceServlet.dispatchToEjbEndpoint(EjbWebServiceServlet.java:200)
	at org.glassfish.webservices.EjbWebServiceServlet.service(EjbWebServiceServlet.java:131)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
	at com.sun.grizzly.http.servlet.ServletAdapter$FilterChainImpl.doFilter(ServletAdapter.java:1059)
	at com.sun.grizzly.http.servlet.ServletAdapter$FilterChainImpl.invokeFilterChain(ServletAdapter.java:999)
	at com.sun.grizzly.http.servlet.ServletAdapter.doService(ServletAdapter.java:434)
	at com.sun.grizzly.http.servlet.ServletAdapter.service(ServletAdapter.java:384)
	at com.sun.grizzly.tcp.http11.GrizzlyAdapter.service(GrizzlyAdapter.java:179)
	at com.sun.enterprise.v3.server.HK2Dispatcher.dispath(HK2Dispatcher.java:117)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$Hk2DispatcherCallable.call(ContainerMapper.java:354)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:195)
	at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:860)
	at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:757)
	at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1056)
	at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:229)
	at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
	at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
	at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
	at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
	at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)
	at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)
	at com.sun.grizzly.ContextTask.run(ContextTask.java:71)
	at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:532)
	at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:513)
	at java.lang.Thread.run(Thread.java:744)
|#]

**Comment by DawidCh** [comment]
Is the endpoint deployed properly?
From logs I can only say that it seams that you have different java configured for glassfish and for build. Do you run glassfish with java 1.8?

**Comment by pujarisat** [comment]
Hi @DawidCh 

glassfish  is running on jdk1.7.0_45 .

please find the below screen of asenv.bat file where java path specified 
![image](https://cloud.githubusercontent.com/assets/22190140/18903347/3ade49f0-8576-11e6-8048-6a82ec2ba976.png)

**Comment by DawidCh** [comment]
Questions:
1. Has that issue been raised after library upgrade, which you have described in issue #332 
2. What java version has been used for build?
3. When the problem occurred? Was it working earlier?

**Comment by pujarisat** [comment]
Hi @DawidCh 
please find below Answer
Questions: 
1. Has that issue been raised after library upgrade, which you have described in issue #332 
Answer:  Yes , but I am not deployed any controller in app domain 
2. What java version has been used for build?
Answer: java version for build is : jdk1.7.0_45 ( printing in ant log : java version 1.7)
3. When the problem occurred? Was it working earlier
Answer: it is first time and I am accessing the first time

**Comment by DawidCh** [comment]
1. Is the webservice edpoint deployed?
Basically the exception says that there is java inconsistency in your env.
2. Do you have different java version present in the system?

**Comment by GoebelL** [comment]
Hi @pujarisat 
Where does this APP version come from? Could it be something customized or compiled with later Java version, i.e. JDK 8? Since you are using a JRE 7 - as required for OSCM - the class loader would fail in this case with such an error.

**Comment by pujarisat** [comment]
Thank @DawidCh ,

I will check once again java version and let you know the result as soon as possible .

-Thanks 
Satling

**Comment by StavrevaS** [comment]
The problems are solved.
