### ISSUE TITLE
SOAP Handler has wrong class in SAML_SP mode

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#431]
[Version]
16.1.2

[How to reproduce]
Install the OSCM in SAML_SP mode and see server.log
[#|2016-11-11T08:48:22.170+0100|SEVERE|glassfish3.1.2|javax.enterprise.webservices.org.glassfish.webservices|_ThreadID=1;_ThreadName=Thread-2;|Unable to load handler class org.oscm.ess.converter.SupportedVersionHandler
java.lang.ClassNotFoundException: org.oscm.ess.converter.SupportedVersionHandler
	at com.sun.enterprise.loader.ASURLClassLoader.findClassData(ASURLClassLoader.java:787)
	at com.sun.enterprise.loader.ASURLClassLoader.findClass(ASURLClassLoader.java:696)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.glassfish.webservices.WsUtil.processConfiguredHandlers(WsUtil.java:2141)
	at org.glassfish.webservices.WsUtil.configureJAXWSServiceHandlers(WsUtil.java:2193

**Comment by StavrevaS** [comment]
The class name in webservice-sts.xml is corrected.
