### ISSUE TITLE
NPE in server.lof for eclipse persistence with TimerService in GF4

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#569]
The server.log of bes domain is showing following warnings:

java.lang.NullPointerException
	at org.eclipse.persistence.platform.server.ServerPlatformUtils.createServerPlatform(ServerPlatformUtils.java:99)
	at org.eclipse.persistence.sessions.factories.SessionManager.init(SessionManager.java:77)
	at org.eclipse.persistence.sessions.factories.SessionManager.<clinit>(SessionManager.java:71)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.addSessionToGlobalSessionManager(EntityManagerSetupImpl.java:907)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.initSession(EntityManagerSetupImpl.java:2671)
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:675)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:205)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:305)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:337)
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:303)
	at org.glassfish.persistence.jpa.JPADeployer$2.visitPUD(JPADeployer.java:451)
	at org.glassfish.persistence.jpa.JPADeployer$PersistenceUnitDescriptorIterator.iteratePUDs(JPADeployer.java:510)
	at org.glassfish.persistence.jpa.JPADeployer.iterateInitializedPUsAtApplicationPrepare(JPADeployer.java:492)
	at org.glassfish.persistence.jpa.JPADeployer.event(JPADeployer.java:398)
	at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:131)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:487)
	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:219)
	at org.glassfish.ejb.persistent.timer.PersistentEJBTimerService.deployEJBTimerService(PersistentEJBTimerService.java:1464)
	at org.glassfish.ejb.persistent.timer.PersistentEJBTimerService.initEJBTimerService(PersistentEJBTimerService.java:1370)
	at org.glassfish.ejb.persistent.timer.DistributedEJBTimerService.initPersistentTimerService(DistributedEJBTimerService.java:98)
	at com.sun.ejb.containers.EJBTimerService.initEJBTimerService(EJBTimerService.java:230)
	at com.sun.ejb.containers.EJBTimerService.getEJBTimerService(EJBTimerService.java:205)
	at com.sun.ejb.containers.EJBTimerService.getEJBTimerService(EJBTimerService.java:187)
	at com.sun.ejb.containers.BaseContainer.<init>(BaseContainer.java:825)

This issue is unresolved bug in Glassfish 4.1.1. See this [bug](https://java.net/jira/browse/GLASSFISH-21468).

Glassfish 4.1.1. is using eclipse jpa persistence module 2.6.1 (org.eclipse.persistence.jpa.jar)  and the problem is fixed in the version 2.6.2.
Patch is available for this module fpr 2.6.0.
See this [bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=482894).

We should try to patch GF4.1.1 with the eclipse persistence module 2.6.2.
Check the dependencies

**Comment by grubskim** [comment]
Updated build scripts to overwrite the existing eclipse.persistence libraries with newer versions (2.6.3).

**Comment by kwodzynski** [comment]
Checked on Windows Server 2016, jdk1.8u121, build BES_MASTER_DELIVERY-1019 2017/04/20 in SAML mode. I have not noticed such problems in log files.
