### ISSUE TITLE
Parse error by buidid - playground web test

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/development#570]
Playground test, in the system.log the following error occurs:

02/09/2017_15:45:25.779 FSP_INTS-BSS: ERROR: ThreadID http-listener-1(2): ApplicationBean: 70023: Error formating build date
java.text.ParseException: Unparseable date: "201702"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at org.oscm.ui.beans.ApplicationBean.initBuildIdAndDate(ApplicationBean.java:159)
	at org.oscm.ui.beans.ApplicationBean.getBuildId(ApplicationBean.java:423)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:363)
	at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176)
	at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203)
	at com.sun.el.parser.AstValue.getValue(AstValue.java:140)
	at com.sun.el.parser.AstValue.getValue(AstValue.java:204)
	at com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:226)
	at org.jboss.weld.el.WeldValueExpression.getValue(WeldValueExpression.java:50)

**Comment by DawidCh** [comment]
The name of jenkins job is too long. It is being cut and rest of the date is lost. We should use shorter names than glassfish4_WEB_Playground_estbescirh7
The issue will be fixed later.
