### ISSUE TITLE
AWS controller does not work

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#584]
[Build] 16.1 fix6 17.02.2017

[Steps to reproduce]

  1. update app database to 16.1 fix6
  2. deploy app and aws of 16.1 fix6
  3. go to http://\<mymachine\>:8880/oscm-app (OK)
  4. to to http://\<mymachine\>:8880/oscm-app-aws/ (not OK)

[Expected result]
log in prompted for aws controller

[Observed result]
Window with this information:
Controller Configuration
The following error occurred during the last operation:
Statuscode: 500
Request-URI: /oscm-app-aws/
Servlet name: Faces Servlet
Exception: javax.servlet.ServletException

[Details]
app server.log:
[#|2017-02-27T11:46:15.762+0100|WARNING|glassfish3.1.2|javax.enterprise.system.container.web.com.sun.enterprise.web|_ThreadID=140;_ThreadName=Thread-2;|StandardWrapperValve[Faces Servlet]: PWC1406: Servlet.service() for servlet Faces Servlet threw exception
org.richfaces.skin.SkinNotFoundException: Skin with name interstage not found
	at org.richfaces.skin.AbstractSkinFactory.loadProperties(AbstractSkinFactory.java:133)
	at org.richfaces.skin.AbstractSkinFactory.buildSkin(AbstractSkinFactory.java:107)
	at org.richfaces.skin.AbstractSkinFactory$SkinBuilder.call(AbstractSkinFactory.java:56)
	at org.richfaces.skin.AbstractSkinFactory$SkinBuilder.call(AbstractSkinFactory.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at org.richfaces.skin.AbstractSkinFactory.getSkin(AbstractSkinFactory.java:156)
	at org.richfaces.skin.SkinFactoryImpl.getSkinOrName(SkinFactoryImpl.java:123)
	at org.richfaces.skin.SkinFactoryImpl.getSkin(SkinFactoryImpl.java:60)
	at org.richfaces.resource.CompiledCSSResource.getSkinHashCode(CompiledCSSResource.java:143)
	at org.richfaces.resource.CompiledCSSResource.writeState(CompiledCSSResource.java:218)
	at org.richfaces.resource.ResourceUtils.saveResourceState(ResourceUtils.java:477)
	at org.richfaces.resource.AbstractBaseResource.getRequestPath(AbstractBaseResource.java:153)
	at org.richfaces.resource.mapping.ResourceServletMapping.getResourcePath(ResourceServletMapping.java:101)
	at org.richfaces.resource.mapping.ResourceServletMapping.getMappedPath(ResourceServletMapping.java:86)
	at org.richfaces.resource.mapping.ResourceServletMapping.getResourcePath(ResourceServletMapping.java:72)
	at org.richfaces.resource.external.MappedResourceFactoryImpl.createResource(MappedResourceFactoryImpl.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.richfaces.application.ServiceTracker$1.invoke(ServiceTracker.java:153)
	at com.sun.proxy.$Proxy316.createResource(Unknown Source)
	at org.richfaces.resource.ResourceFactoryImpl.resolveMappedResource(ResourceFactoryImpl.java:393)
	at org.richfaces.resource.ResourceFactoryImpl.createMappedResource(ResourceFactoryImpl.java:360)
	at org.richfaces.resource.ResourceFactoryImpl.createResource(ResourceFactoryImpl.java:343)
	at org.richfaces.resource.ResourceHandlerImpl.createResource(ResourceHandlerImpl.java:266)
	at org.richfaces.resource.ResourceHandlerImpl.createResource(ResourceHandlerImpl.java:280)
	at com.sun.faces.renderkit.html_basic.StylesheetRenderer.encodeEnd(StylesheetRenderer.java:97)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:877)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1826)
	at com.sun.faces.renderkit.html_basic.HeadRenderer.encodeHeadResources(HeadRenderer.java:105)
	at com.sun.faces.renderkit.html_basic.HeadRenderer.encodeEnd(HeadRenderer.java:92)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:877)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1826)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1822)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:447)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:125)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:286)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:286)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:139)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:594)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1550)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:281)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:655)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:595)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:161)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:331)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:231)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$AdapterCallable.call(ContainerMapper.java:317)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:195)
	at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:860)
	at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:757)
	at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1056)
	at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:229)
	at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
	at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
	at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
	at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
	at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)
	at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)
	at com.sun.grizzly.ContextTask.run(ContextTask.java:71)
	at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:532)
	at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:513)
	at java.lang.Thread.run(Thread.java:744)
|#]

**Comment by StavrevaS** [comment]
It is the same with openstack controller

**Comment by DawidCh** [comment]
Is it glassfish4 or 3?

**Comment by SylviaDehn** [comment]
glassfish3

**Comment by MiethanerR** [comment]
I can't reproduce this with OSCM or ESCM version. Are you sure this isn't a caching problem?

**Comment by toshihiro-shiino** [comment]
this issue occurs in my environment, too.
ESCM v16.1 fix6, Oracle JDK 7u45, glassfish3, oscm-app-openstack.ear

**Comment by SylviaDehn** [comment]
This error also occurs in the GL4 branch with internal mode.

**Comment by GoebelL** [comment]
@MiethanerR 
Please check again and try to find a workaround.

**Comment by MiethanerR** [comment]
Fixed the packaging for app common in the controllers. Please be aware that you have to delete the cache of glassfish if redeploy the controllers.

Steps:
1. Undeploy APP and all controllers
2. Stop the domain
3. Delete the folders "generated" and osgi-cache. Also all app and controller related folders in applications and applications/__internal
4. Start domain
5. Deploy new APP and controllers

**Comment by MiethanerR** [comment]
I also fixed a wrong classpath in the manifest of app-startup.

**Comment by SylviaDehn** [comment]
[Build] 2017/03/14 verified

**Comment by MiethanerR** [comment]
Fixed followup problem with missing jar in vmware controller.

**Comment by victorhrsilva** [comment]
Checked on Windows Server 2012, jdk1.8u121, biuld: GLASSFISH4_EE_UNIT-89 2017/04/19 in SAML mode. The controllers AWS, OpenStack and VMWare and the problem does not occur.
