### ISSUE TITLE
Service and subscription search does not work; Indexes not created properly at system startup

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#589]
[Version]
16.1 fix6+ 2017/02/27

[How to reproduce]
1. stop bes and master-indexer domain.
2. manually delete all index files.    
3. start domains

[Expected result]
all hibernate search index files are created, and search works for services and subscriptions

[Observed result]
Service and subscription search does not work

[Details]
See below screenshot of example of subscription index files. Looks like something is locked here. 

**system log file of master-indexer-domain:**
[2017-03-01T13:40:13.339+0100] [glassfish 4.1] [ERROR] [] [org.hibernate.resource.transaction.internal.SynchronizationRegistryStandardImpl] [tid: _ThreadID=122 _ThreadName=p: thread-pool-1; w: 26] [timeMillis: 1488372013339] [levelValue: 1000] [[
  HHH000260: Exception calling user Synchronization [org.hibernate.search.backend.impl.EventSourceTransactionContext$BeforeCommitSynchronizationDelegator@5c448474] : java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils]]

[2017-03-01T13:40:13.339+0100] [glassfish 4.1] [WARNING] [jts.unexpected_error_occurred_in_after_completion] [javax.enterprise.system.core.transaction.com.sun.jts.jta] [tid: _ThreadID=122 _ThreadName=p: thread-pool-1; w: 26] [timeMillis: 1488372013339] [levelValue: 900] [[
  JTS5054: Unexpected error occurred in after completion
org.hibernate.resource.transaction.LocalSynchronizationException: Exception calling user Synchronization (beforeCompletion): org.hibernate.search.backend.impl.EventSourceTransactionContext$BeforeCommitSynchronizationDelegator
	at org.hibernate.resource.transaction.internal.SynchronizationRegistryStandardImpl.notifySynchronizationsBeforeTransactionCompletion(SynchronizationRegistryStandardImpl.java:65)
	at org.hibernate.resource.transaction.backend.jta.internal.JtaTransactionCoordinatorImpl.beforeCompletion(JtaTransactionCoordinatorImpl.java:327)
	at org.hibernate.resource.transaction.backend.jta.internal.synchronization.SynchronizationCallbackCoordinatorNonTrackingImpl.beforeCompletion(SynchronizationCallbackCoordinatorNonTrackingImpl.java:47)
	at org.hibernate.resource.transaction.backend.jta.internal.synchronization.RegisteredSynchronization.beforeCompletion(RegisteredSynchronization.java:37)
	at com.sun.jts.jta.SynchronizationImpl.before_completion(SynchronizationImpl.java:99)
	at com.sun.jts.CosTransactions.RegisteredSyncs.distributeBefore(RegisteredSyncs.java:141)
	at com.sun.jts.CosTransactions.TopCoordinator.beforeCompletion(TopCoordinator.java:2548)
	at com.sun.jts.CosTransactions.CoordinatorTerm.commit(CoordinatorTerm.java:249)
	at com.sun.jts.CosTransactions.TerminatorImpl.commit(TerminatorImpl.java:231)
	at com.sun.jts.CosTransactions.CurrentImpl.commit(CurrentImpl.java:622)
	at com.sun.jts.jta.TransactionManagerImpl.commit(TransactionManagerImpl.java:331)
	at com.sun.enterprise.transaction.jts.JavaEETransactionManagerJTSDelegate.commitDistributedTransaction(JavaEETransactionManagerJTSDelegate.java:186)
	at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.commit(JavaEETransactionManagerSimplified.java:859)
	at com.sun.ejb.containers.EJBContainerTransactionManager.completeNewTx(EJBContainerTransactionManager.java:723)
	at com.sun.ejb.containers.EJBContainerTransactionManager.postInvokeTx(EJBContainerTransactionManager.java:507)
	at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4566)
	at org.glassfish.ejb.mdb.MessageBeanContainer.afterMessageDeliveryInternal(MessageBeanContainer.java:1326)
	at org.glassfish.ejb.mdb.MessageBeanContainer.afterMessageDelivery(MessageBeanContainer.java:1301)
	at org.glassfish.ejb.mdb.MessageBeanListenerImpl.afterMessageDelivery(MessageBeanListenerImpl.java:86)
	at com.sun.enterprise.connectors.inbound.MessageEndpointInvocationHandler.invoke(MessageEndpointInvocationHandler.java:143)
	at com.sun.proxy.$Proxy279.afterDelivery(Unknown Source)
	at com.sun.messaging.jms.ra.OnMessageRunner.run(OnMessageRunner.java:361)
	at com.sun.enterprise.connectors.work.OneWork.doWork(OneWork.java:107)
	at com.sun.corba.ee.impl.threadpool.ThreadPoolImpl$WorkerThread.performWork(ThreadPoolImpl.java:497)
	at com.sun.corba.ee.impl.threadpool.ThreadPoolImpl$WorkerThread.run(ThreadPoolImpl.java:540)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/lang3/StringUtils
	at org.oscm.domobjects.bridge.SubscriptionClassBridge.set(SubscriptionClassBridge.java:118)
	at org.hibernate.search.bridge.util.impl.ContextualExceptionBridgeHelper$OneWayConversionContextImpl.set(ContextualExceptionBridgeHelper.java:110)
	at org.hibernate.search.engine.spi.DocumentBuilderIndexedEntity.buildDocumentFieldForClassBridges(DocumentBuilderIndexedEntity.java:778)
	at org.hibernate.search.engine.spi.DocumentBuilderIndexedEntity.buildDocumentFields(DocumentBuilderIndexedEntity.java:412)
	at org.hibernate.search.engine.spi.DocumentBuilderIndexedEntity.getDocument(DocumentBuilderIndexedEntity.java:351)
	at org.hibernate.search.engine.spi.DocumentBuilderIndexedEntity.createUpdateWork(DocumentBuilderIndexedEntity.java:266)
	at org.hibernate.search.engine.spi.DocumentBuilderIndexedEntity.addWorkToQueue(DocumentBuilderIndexedEntity.java:208)
	at org.hibernate.search.engine.impl.WorkPlan$PerEntityWork.enqueueLuceneWork(WorkPlan.java:521)
	at org.hibernate.search.engine.impl.WorkPlan$PerClassWork.enqueueLuceneWork(WorkPlan.java:283)
	at org.hibernate.search.engine.impl.WorkPlan.getPlannedLuceneWork(WorkPlan.java:155)
	at org.hibernate.search.backend.impl.WorkQueue.prepareWorkPlan(WorkQueue.java:114)
	at org.hibernate.search.backend.impl.BatchedQueueingProcessor.prepareWorks(BatchedQueueingProcessor.java:55)
	at org.hibernate.search.backend.impl.PostTransactionWorkQueueSynchronization.beforeCompletion(PostTransactionWorkQueueSynchronization.java:64)
	at org.hibernate.search.backend.impl.EventSourceTransactionContext$BeforeCommitSynchronizationDelegator.beforeCompletion(EventSourceTransactionContext.java:204)
	at org.hibernate.resource.transaction.internal.SynchronizationRegistryStandardImpl.notifySynchronizationsBeforeTransactionCompletion(SynchronizationRegistryStandardImpl.java:60)
	... 24 more
]]

**Comment by SylviaDehn** [comment]
![subscriptiondirectory](https://cloud.githubusercontent.com/assets/15086024/23460563/42421f80-fe86-11e6-9359-05c76676f04e.jpg)

**Comment by kowalczyka** [comment]
Issue has been fixed with the commit https://github.com/servicecatalog/development/commit/81e30917cd127e618110b7d3af9c557150f2b037

[Details of fix]
Missing library added.

[Fixed build]
glassfish4_EE_UNIT #57

**Comment by SylviaDehn** [comment]
[Build] 16.1 fix6+ 2017/03/10 verified
