### ISSUE TITLE
search for service does not work

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#607]
[Version]
16.1 fix6+ 2017/03/15

[How to reproduce]
1. update search index or create a new subscription
2. search for service

[Expected result]
service is found after a while

[Observed result]
service is not found

[Details]
bes server.log file:
[2017-03-15T14:19:57.906+0100] [glassfish 4.1] [ERROR] [] [org.hibernate.search.store.impl.FSSlaveDirectoryProvider] [tid: _ThreadID=127 _ThreadName=pool-8-thread-1] [timeMillis: 1489583997906] [levelValue: 1000] [[
  HSEARCH000021: Unable to synchronize source of C:\glassfish4\glassfish\domains\bes\slaveIndexBase\org.oscm.domobjects.Subscription
java.nio.file.AccessDeniedException: C:\glassfish4\glassfish\domains\bes\slaveIndexBase\org.oscm.domobjects.Subscription\2\_5.cfs
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at org.hibernate.search.util.impl.FileHelper$1.visitFile(FileHelper.java:204)
	at org.hibernate.search.util.impl.FileHelper$1.visitFile(FileHelper.java:201)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.hibernate.search.util.impl.FileHelper.delete(FileHelper.java:201)
	at org.hibernate.search.util.impl.FileHelper.delete(FileHelper.java:182)
	at org.hibernate.search.util.impl.FileHelper.synchronize(FileHelper.java:115)
	at org.hibernate.search.store.impl.FSSlaveDirectoryProvider$CopyDirectory.run(FSSlaveDirectoryProvider.java:353)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]

**Comment by DawidCh** [comment]
Search in our bugzilla for similar issues.
Try to play with access rights to the folder with indexing or running glassfish with admin rights (?).

**Comment by kowalczyka** [comment]
The issue is reproducable but it occurs randomly. 

It can be reproduced during invocation of development/oscm-portal-webtests/tests/marketplace/testSearchServices.xml suite in my local environment - it does not occur on CI environment.

Problem can be in Windows operating system (on local machine). I will investigate further.

**Comment by DawidCh** [comment]
@kowalczyka May #586 be related or cause of this bug?

**Comment by DawidCh** [comment]
Basically the file which suppose to be deleted upon synchronization is locked by the java process which runs the glassfish. I do not know yet why, but the problem is known to hibernate as javadoc says:

> IOException if it wasn't possible to delete all content which is a common problem on Windows systems.

I will investigate now, why java locks the file.

**Comment by DawidCh** [comment]
According the settings we have following situation:
1.	Master indexer synchronizes it’s directory with “common, remote folder” every 60 seconds.
2.	Bes domain checks “common, remote folder” every 5 seconds looking for a change.
It doesn’t make much sense for me to check every 5 seconds from bes domain. I will set it to 30 seconds.

**Comment by DawidCh** [comment]
The bug seems to be fixed. Commit 5c694379baf6a199a4650e8c7e8572b5c62b1136 fixing the bug.
@Testers - please pay attention during different tests to keep eye on the logs if the bug is really fixed.

**Comment by DawidCh** [comment]
Just a hint: if you have domain already set up and do not want to rebuild the environment following option needs to be added in JVM options under server-config in glassfish:

> -Dhibernate.search.default.locking_strategy=single

**Comment by kwodzynski** [comment]
Checked on Glassfish 4, jdk1.8.0u121, build GLASSFISH4_EE_UNIT-852017/04/06 in SAML mode.
The both searchers are working correctly, I've got no errors in logfiles.

**Comment by DawidCh** [comment]
Reopen as the bug came back on windows during webtests.

**Comment by kowalczyka** [comment]
It seems that the problem occured a few years ago - https://forum.hibernate.org/viewtopic.php?f=9&t=1024650&start=0&sid=bfe06b9f460f7dc1b61c2ea44eeeffa9.

Setting the hibernate.search.reader.strategy to not shared seem to resolve our issue - I can't reproduce the issue anymore.

**Comment by kwodzynski** [comment]
Checked on Windows Server 2016, jdk1.8u121, glassfish 4, build: BES_MASTER_DELIVERY-10192017/04/20 in SAML mode. I have been checking it since a few days on different builds. I've got no errors in log file.
