### ISSUE TITLE
aws installation fails 

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#643]
[Build] 16.1 fix7 17.02.2017

[Steps to reproduce]
1. fill out properties files for aws
2. call ant -f build-db initDB
3. call ant -f build-glassfish.xml SETUP

[Expected result]
app DB is initialized and domain setup correctly

[Observed result]
app DB is setup ok; domain setup is successful, but the following SEVERE error occurs.

[Details]
The file configuration-attributes.properties looks strange, an extra blank is added in the continuation line:
attributes=server-config.java-config.classpath-suffix=${glassfish.classpath}#server.thread-pools.thread-pool.http-thread-pool.max-thread-pool-size=120#server.network-config.protocols.protocol.http-listener-1.http.xpowered-by=false#server.network-config.protocols.protocol.http-listener-2.http.xpowered-by=false#server.network-config.protocols.protocol.admin-listener.http.xpowered-by=false#configs.config.server-config.system-property.JMS_PROVIDER_PORT.value=**${glassfish.app.domain.portbase}76#\
  server.jms-service.type=LOCAL**

[2017-04-03T14:48:13.452+0200] [glassfish 4.1] [WARNING] [rardeployment.exception_on_invoke_setter] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.connectors.util] [tid: _ThreadID=20 _ThreadName=RunLevelControllerThread-1491223648511] [timeMillis: 1491223693452] [levelValue: 900] [[
  RAR7096: Exception For input string: "${glassfish.app.domain.portbase}76" while trying to set the value ${glassfish.app.domain.portbase}76 on property BrokerPort ]]

[2017-04-03T14:48:13.452+0200] [glassfish 4.1] [SEVERE] [rardeployment.start_failed] [javax.enterprise.resource.resourceadapter.com.sun.enterprise.connectors] [tid: _ThreadID=20 _ThreadName=RunLevelControllerThread-1491223648511] [timeMillis: 1491223693452] [levelValue: 1000] [[
  RAR6035 : Resource adapter start failed.
com.sun.appserv.connectors.internal.api.ConnectorRuntimeException: Wrong parameters for pool creation : For input string: "${glassfish.app.domain.portbase}76"
	at com.sun.enterprise.connectors.ActiveOutboundResourceAdapter.loadRAConfiguration(ActiveOutboundResourceAdapter.java:332)
	at com.sun.enterprise.connectors.jms.system.ActiveJmsResourceAdapter.loadRAConfiguration(ActiveJmsResourceAdapter.java:397)
	at com.sun.enterprise.connectors.ActiveOutboundResourceAdapter.init(ActiveOutboundResourceAdapter.java:115)
	at com.sun.enterprise.connectors.inbound.ActiveInboundResourceAdapterImpl.init(ActiveInboundResourceAdapterImpl.java:90)
	at com.sun.enterprise.connectors.ActiveRAFactory.instantiateActiveResourceAdapter(ActiveRAFactory.java:141)
	at com.sun.enterprise.connectors.ActiveRAFactory.createActiveResourceAdapter(ActiveRAFactory.java:108)
	at com.sun.enterprise.connectors.service.ResourceAdapterAdminServiceImpl.createActiveResourceAdapter(ResourceAdapterAdminServiceImpl.java:210)
	at com.sun.enterprise.connectors.service.ResourceAdapterAdminServiceImpl.createActiveResourceAdapter(ResourceAdapterAdminServiceImpl.java:346)
	at com.sun.enterprise.connectors.ConnectorRuntime.createActiveResourceAdapter(ConnectorRuntime.java:405)
	at com.sun.enterprise.connectors.jms.system.JmsProviderLifecycle.initializeBroker(JmsProviderLifecycle.java:127)
	at com.sun.enterprise.connectors.jms.system.JmsProviderLifecycle.postConstruct(JmsProviderLifecycle.java:106)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:326)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:228)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2072)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.sun.appserv.connectors.internal.api.ConnectorRuntimeException: For input string: "${glassfish.app.domain.portbase}76"
	at com.sun.enterprise.connectors.util.SetMethodAction.handleException(SetMethodAction.java:151)
	at com.sun.enterprise.connectors.util.SetMethodAction.run(SetMethodAction.java:128)
	at com.sun.enterprise.connectors.ActiveOutboundResourceAdapter.loadRAConfiguration(ActiveOutboundResourceAdapter.java:329)
	... 23 more
Caused by: java.lang.NumberFormatException: For input string: "${glassfish.app.domain.portbase}76"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:569)
	at java.lang.Integer.valueOf(Integer.java:766)
	at com.sun.enterprise.deployment.EnvironmentProperty.getValueObjectUsingAllowedTypes(EnvironmentProperty.java:400)
	at com.sun.enterprise.deployment.EnvironmentProperty.getObjectFromString(EnvironmentProperty.java:351)
	at com.sun.enterprise.deployment.EnvironmentProperty.getResolvedValueObject(EnvironmentProperty.java:162)
	at com.sun.enterprise.connectors.util.SetMethodAction.run(SetMethodAction.java:126)
	... 24 more
]]

[2017-04-03T14:48:13.640+0200] [glassfish 4.1] [SEVERE] [] [] [tid: _ThreadID=20 _ThreadName=Thread-9] [timeMillis: 1491223693640] [levelValue: 1000] [[
  com.sun.appserv.connectors.internal.api.ConnectorRuntimeException: Failed to start resource adapter : Wrong parameters for pool creation : For input string: "${glassfish.app.domain.portbase}76"
	at com.sun.enterprise.connectors.ActiveOutboundResourceAdapter.init(ActiveOutboundResourceAdapter.java:141)
	at com.sun.enterprise.connectors.inbound.ActiveInboundResourceAdapterImpl.init(ActiveInboundResourceAdapterImpl.java:90)
	at com.sun.enterprise.connectors.ActiveRAFactory.instantiateActiveResourceAdapter(ActiveRAFactory.java:141)
	at com.sun.enterprise.connectors.ActiveRAFactory.createActiveResourceAdapter(ActiveRAFactory.java:108)
	at com.sun.enterprise.connectors.service.ResourceAdapterAdminServiceImpl.createActiveResourceAdapter(ResourceAdapterAdminServiceImpl.java:210)
	at com.sun.enterprise.connectors.service.ResourceAdapterAdminServiceImpl.createActiveResourceAdapter(ResourceAdapterAdminServiceImpl.java:346)
	at com.sun.enterprise.connectors.ConnectorRuntime.createActiveResourceAdapter(ConnectorRuntime.java:405)
	at com.sun.enterprise.connectors.jms.system.JmsProviderLifecycle.initializeBroker(JmsProviderLifecycle.java:127)
	at com.sun.enterprise.connectors.jms.system.JmsProviderLifecycle.postConstruct(JmsProviderLifecycle.java:106)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:326)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:228)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2072)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:114)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:88)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.sun.appserv.connectors.internal.api.ConnectorRuntimeException: For input string: "${glassfish.app.domain.portbase}76"
	at com.sun.enterprise.connectors.util.SetMethodAction.handleException(SetMethodAction.java:151)
	at com.sun.enterprise.connectors.util.SetMethodAction.run(SetMethodAction.java:128)
	at com.sun.enterprise.connectors.ActiveOutboundResourceAdapter.loadRAConfiguration(ActiveOutboundResourceAdapter.java:329)
	at com.sun.enterprise.connectors.jms.system.ActiveJmsResourceAdapter.loadRAConfiguration(ActiveJmsResourceAdapter.java:397)
	at com.sun.enterprise.connectors.ActiveOutboundResourceAdapter.init(ActiveOutboundResourceAdapter.java:115)
	... 21 more
Caused by: java.lang.NumberFormatException: For input string: "${glassfish.app.domain.portbase}76"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:569)
	at java.lang.Integer.valueOf(Integer.java:766)
	at com.sun.enterprise.deployment.EnvironmentProperty.getValueObjectUsingAllowedTypes(EnvironmentProperty.java:400)
	at com.sun.enterprise.deployment.EnvironmentProperty.getObjectFromString(EnvironmentProperty.java:351)
	at com.sun.enterprise.deployment.EnvironmentProperty.getResolvedValueObject(EnvironmentProperty.java:162)
	at com.sun.enterprise.connectors.util.SetMethodAction.run(SetMethodAction.java:126)
	... 24 more]]

**Comment by kwodzynski** [comment]
Checked on Glassfish4, Windows Server 2016, jdk1.8.0u121, build glassfish4_EE_UNIT#83 in SAML mode. The severe errors in logs do not occurs.
