### ISSUE TITLE
Strange severe error in logs caused by a Sun JVM bug

### ISSUE THREAD

**Issue by kwodzynski** [servicecatalog/development#679]
Glassfish 4
jdk 1.8u121
Windows Server 2016
build BES_MASTER_DELIVERY-10192017/04/20
SAML mode

In Bes and App domains I found following problem:

[2017-04-22T11:19:47.826+0200] [glassfish 4.1] [SEVERE] [] [] [tid: _ThreadID=1132 _ThreadName=Thread-9] [timeMillis: 1492852787826] [levelValue: 1000] [[
  Exception in thread "AWT-EventQueue-0"]]

[2017-04-22T11:19:47.826+0200] [glassfish 4.1] [SEVERE] [] [] [tid: _ThreadID=1132 _ThreadName=Thread-9] [timeMillis: 1492852787826] [levelValue: 1000] [[
  java.lang.ClassCastException: sun.java2d.HeadlessGraphicsEnvironment cannot be cast to sun.awt.Win32GraphicsEnvironment
	at sun.awt.windows.WToolkit$3.run(WToolkit.java:834)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)]]

Above problem occurs when I close remotely connection with workstation. I found information on Internet that the problem depends on environment and hardware (for example on my laptop I cannot see the problem). As well I found solution: remove -Djava.awt.headless=true from JVM options. I did it for app domain and indeed the problem no longer occurs. But I am not sure if we need that jvm option in our settings. Maybe it is important to set the option for proper working of application.

To consider and make a decision.

**Comment by DawidCh** [comment]
Fixed by removing java.awt.headless property.

**Comment by kwodzynski** [comment]
Checked on Windows Server 2016, jdk1.8u121, build US9442 EXPORT USAGE UT-14 2017/05/24. The error no longer occurs.

**Comment by DawidCh** [comment]
Reopened because proposed solution is not good.

**Comment by DawidCh** [comment]
The change has been applied for bes domain, as this domain produced too many logging informations.

**Comment by kwodzynski** [comment]
Checked on Windows Server 2016, jdk1.8u121, build US9442 EXPORT USAGE UT-18 2017/05/26 in SAML mode. The error no longer occurs.

**Comment by kwodzynski** [comment]
Retested on Windows Server 2016, jdk1.8u121, build BES_MASTER_UNIT-1778 2017/06/29 (Official 17.2.0) in Saml mode. The error no longer occurs.
