### ISSUE TITLE
Vmware adapter upgrade install: Recommended install order does not work

### ISSUE THREAD

**Issue by AndreasTWolf** [servicecatalog/development#769]
[Version]
V17.0.2

[Date]
2017/06/08

[Test category]
Creative

[Description]
Vmware adapter upgrade install: Recommended install order does not work
update installation; changes of target VMware system, therefore deleting of the content of the vmware database with >ant -f build-db-import.xml deleteAll -Ddb.dir=controller_db
works ok;
running the target: > ant -f build-db-import.xml importVCenter -Ddb.dir=controller_db
works ok;

running the target: >ant -f build-db-import.xml importCluster -Ddb.dir=controller_db
Buildfile: C:\Software\CT-MG\17.01\vmware-install\install\build-db-import.xml
ERROR:
importCluster:
     [java] ClusterImport execute failed to add row:  estvcsadev.intern.est.fujitsu.com EST esscluster
     [java] ClusterImport execute Failed to retrieve datacenter EST
     [java] ClusterImport execute failed to import cluster.
     [java] java.lang.RuntimeException: Failed to retrieve datacenter EST
     [java]     at org.oscm.app.vmware.db.importer.ClusterImport.getDatacenterKey(ClusterImport.java:129)
     [java]     at org.oscm.app.vmware.db.importer.ClusterImport.addTableRow(ClusterImport.java:94)
     [java]     at org.oscm.app.vmware.db.importer.ClusterImport.execute(ClusterImport.java:58)
     [java]     at org.oscm.app.vmware.db.importer.ClusterImport.main(ClusterImport.java:36)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java]     at java.lang.reflect.Method.invoke(Method.java:498)
     [java]     at org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:221)
     [java]     at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:154)
     [java]     at org.apache.tools.ant.taskdefs.Java.run(Java.java:834)
     [java]     at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:228)
     [java]     at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:137)
     [java]     at org.apache.tools.ant.taskdefs.Java.execute(Java.java:110)
     [java]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [java]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java]     at java.lang.reflect.Method.invoke(Method.java:498)
     [java]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
     [java]     at org.apache.tools.ant.Task.perform(Task.java:348)
     [java]     at org.apache.tools.ant.Target.execute(Target.java:435)
     [java]     at org.apache.tools.ant.Target.performTasks(Target.java:456)
     [java]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
     [java]     at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
     [java]     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
     [java]     at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
     [java]     at org.apache.tools.ant.Main.runBuild(Main.java:857)
     [java]     at org.apache.tools.ant.Main.startAnt(Main.java:236)
     [java]     at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
     [java]     at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)

BUILD FAILED
C:\Software\CT-MG\17.01\vmware-install\install\build-db-import.xml:48: java.lang.RuntimeException: Failed to retrieve da
tacenter EST
        at org.oscm.app.vmware.db.importer.ClusterImport.getDatacenterKey(ClusterImport.java:129)
        at org.oscm.app.vmware.db.importer.ClusterImport.addTableRow(ClusterImport.java:94)
        at org.oscm.app.vmware.db.importer.ClusterImport.execute(ClusterImport.java:58)
        at org.oscm.app.vmware.db.importer.ClusterImport.main(ClusterImport.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:221)
        at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:154)
        at org.apache.tools.ant.taskdefs.Java.run(Java.java:834)
        at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:228)
        at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:137)
        at org.apache.tools.ant.taskdefs.Java.execute(Java.java:110)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:857)
        at org.apache.tools.ant.Main.startAnt(Main.java:236)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)

Total time: 0 seconds

[Steps to reproduce]
see above
[Expected result]
I can install the cvs files in the described order
[Observed result]
error
[Details]
See above;

When calling the (not described) target 
>ant -f build-db-import.xml importDatacenter -Ddb.dir=controller_db 
and then 
>ant -f build-db-import.xml importCluster -Ddb.dir=controller_db 
it works
[Messages and logs]
See documentation:
VMware vSphere Integration (GlassFish)
B1WS-1281-01 May 2017
2.4 Update Installation
Updating the vmware Database Step 3 to 5,

**Comment by GoebelL** [comment]
@gertipoppel 
Please switch the order of the two mentioned steps in the VMware vSphere Integration Guide.

**Comment by gertipoppel** [comment]
Fixed in the VMware vSphere Integration Guide. Will be available with V17.2
