### ISSUE TITLE
Custom attributes have no effect when custom tab is used; and no effect if number of VMs (usage info)  is requested

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#788]
[Build] 17.2 2017/06/29

[Steps to reproduce]
1. to test if credentials work using custom attributes, I first updated my app db with an incorrect API_USER_PWD for openstack e.g. _crypt:badpassword
2. restart app domain
3. As user with role tech. provider and supplier define custom attribute API_USER_PWD id
for ess.openstack for all customers use option encryption and enter the CORRECT pwd
4. As customer create an openstack subscription
5. After subscription is created, check "My Subscriptions"

[Expected result]
subscription is created; and  "My Subscriptions" custom tab for the subscription shows VM info

[Observed result]
subscription is created, but authentication error happens when custom tab is clicked. (The VMs section stays empty)
app-openstack.log:
[07/03 15:13:21] [http-listener-1(1)] ERROR Failed to connect to Nova: unauthorized (HTTP 401, URI http://10.140.18.120/identity/v3/auth/tokens, responseBody {"error": {"message": "The request you have made requires authentication.", "code": 401, "title": "Unauthorized"}}): Server returned HTTP response code: 401 for URL: http://10.140.18.120/identity/v3/auth/tokens
org.oscm.app.v2_0.exceptions.APPlatformException: Failed to connect to Nova: unauthorized (HTTP 401, URI http://10.140.18.120/identity/v3/auth/tokens, responseBody {"error": {"message": "The request you have made requires authentication.", "code": 401, "title": "Unauthorized"}}): Server returned HTTP response code: 401 for URL: http://10.140.18.120/identity/v3/auth/tokens
	at org.oscm.app.openstack.controller.OpenStackInstanceAccess.getServerDetails(OpenStackInstanceAccess.java:75)
	at org.oscm.app.common.instanceDetail.ExtensionInterfaceBean.getInstanceDetails(ExtensionInterfaceBean.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:363)

[Details]
In the app db, the customattribute table does have an entry for  API_USER_PWD as expected.
But it looks like the configurationsettings value (where API_USER_PWD is wrong) is used instead.
The method that updates the number of VMs also seems to use the wrong password, as the number of VMs is not updated.
The same problem exists with AWS.

**Comment by MiethanerR** [comment]
Fixed. The cause was a missing flag for the overwrite for method calls originating from the extension interface or similar.

**Comment by SylviaDehn** [comment]
Tested number of VMs and Custom Tab using openstack

**Comment by kwodzynski** [comment]
Retested on Windows Server 2016, jdk1.8u131, build BES_MASTER_UNIT-1904 2017/07/27 (official 17.3.0) in SAML mode. 
It works as expected.
