### ISSUE TITLE
operation failed when F5 is pressed at end of subscription process

### ISSUE THREAD

**Issue by SylviaDehn** [servicecatalog/development#811]
[Build] 17.3 2017/07/27

[Steps to reproduce]
1. log-in as customer and subscribe to async service
2. service is shown as pending at end of subscription dialog
3. customer presses F5 to see if service is ready.   
4. dialog with "confirm form re-submission" is shown;  press continue

[Expected result]
redirect to account/subscriptions page or redisplay of subscription 

[Observed result]
operation failed message is displayed

[Details]
this does not look nice. It is possible to enter marketplace url again and get out of the operation failed.
server.log:
[2017-07-31T11:33:17.809+0200] [glassfish 4.1] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=30 _ThreadName=http-listener-1(3)] [timeMillis: 1501493597809] [levelValue: 900] [[
  StandardWrapperValve[Faces Servlet]: Servlet.service() for servlet Faces Servlet threw exception
org.jboss.weld.context.NonexistentConversationException: WELD-000321: No conversation found to restore for id 2
	at org.jboss.weld.context.AbstractConversationContext.initialize(AbstractConversationContext.java:259)
	at org.jboss.weld.context.http.LazyHttpConversationContextImpl.initialize(LazyHttpConversationContextImpl.java:90)
	at org.jboss.weld.context.http.LazyHttpConversationContextImpl.checkContextInitialized(LazyHttpConversationContextImpl.java:124)
	at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:74)
	at org.jboss.weld.context.AbstractContext.get(AbstractContext.java:114)
	at org.jboss.weld.context.PassivatingContextWrapper$AbstractPassivatingContextWrapper.get(PassivatingContextWrapper.java:70)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:96)
	at org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.get(ContextualInstanceStrategy.java:178)
	at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:50)
	at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:761)
	at org.jboss.weld.el.AbstractWeldELResolver.lookup(AbstractWeldELResolver.java:107)
	at org.jboss.weld.el.AbstractWeldELResolver.getValue(AbstractWeldELResolver.java:90)
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:188)
	at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176)
	at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203)
	at com.sun.el.parser.AstIdentifier.getValue(AstIdentifier.java:116)
	at com.sun.el.parser.AstValue.getBase(AstValue.java:151)
	at com.sun.el.parser.AstValue.getValue(AstValue.java:200)
	at com.sun.el.parser.AstAnd.getValue(AstAnd.java:58)
	at com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:226)
	at org.jboss.weld.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:109)
	at com.sun.el.parser.AstIdentifier.getValue(AstIdentifier.java:112)
	at com.sun.el.parser.AstEmpty.getValue(AstEmpty.java:66)
	at com.sun.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:226)
	at org.jboss.weld.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:109)
......

**Comment by GoebelL** [comment]
JSF navigation is based on form submission with HTTP POST. Solution for writing actions is to apply a PRG pattern in order to prevent reissuing the POST request and subsequent trouble invoked by F5 or browser refresh.

**Comment by SylviaDehn** [comment]
[Build] 17.4 2017/09/07 verified
