### ISSUE TITLE
VMware controller: loadbalancer configuration not loaded 

### ISSUE THREAD

**Issue by uhu133** [servicecatalog/development#923]
we are trying to use the loadbalancer of the VMware controller.
We are setting a loadbalancer configuration on the VMware cluster:

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<essvcenter>
	<balancer class="org.oscm.app.vmware.business.balancer.DynamicEquipartitionHostBalancer" cpuWeight="" memoryWeight="" vmWeight="" />
</essvcenter>

When provisioning a service the following exception occurs:

org.apache.commons.configuration2.ex.ConfigurationException: Load operation not properly initialized! Do not call read(InputStream) directly, but use a FileHandler to load a configuration.
        at org.apache.commons.configuration2.XMLConfiguration.load(XMLConfiguration.java:1014)
        at org.apache.commons.configuration2.XMLConfiguration.read(XMLConfiguration.java:984)
        at org.oscm.app.vmware.business.balancer.LoadBalancerConfiguration.initialize(LoadBalancerConfiguration.java:62)
        at org.oscm.app.vmware.business.balancer.LoadBalancerConfiguration.<init>(LoadBalancerConfiguration.java:48)
        at org.oscm.app.vmware.business.Template.setHostAndStorage(Template.java:431)
        at org.oscm.app.vmware.business.Template.cloneVM(Template.java:138)
        at org.oscm.app.vmware.business.statemachine.CreateActions.createVM(CreateActions.java:95)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.oscm.app.vmware.business.statemachine.States.invokeAction(States.java:74)
        at org.oscm.app.vmware.business.statemachine.StateMachine.executeAction(StateMachine.java:98)
        at org.oscm.app.vmware.service.VMController.getInstanceStatus(VMController.java:177)
        at sun.reflect.GeneratedMethodAccessor192.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
        at org.apache.openejb.monitoring.StatsInterceptor.record(StatsInterceptor.java:181)
        at org.apache.openejb.monitoring.StatsInterceptor.invoke(StatsInterceptor.java:100)
        at sun.reflect.GeneratedMethodAccessor143.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
        at org.apache.openejb.core.interceptor.InterceptorStack.invoke(InterceptorStack.java:85)
        at org.apache.openejb.core.stateless.StatelessContainer._invoke(StatelessContainer.java:252)
        at org.apache.openejb.core.stateless.StatelessContainer.invoke(StatelessContainer.java:212)
        at org.apache.openejb.core.ivm.EjbObjectProxyHandler.synchronizedBusinessMethod(EjbObjectProxyHandler.java:265)
        at org.apache.openejb.core.ivm.EjbObjectProxyHandler.businessMethod(EjbObjectProxyHandler.java:260)
        at org.apache.openejb.core.ivm.EjbObjectProxyHandler._invoke(EjbObjectProxyHandler.java:89)
        at org.apache.openejb.core.ivm.BaseEjbProxyHandler.invoke(BaseEjbProxyHandler.java:347)
        at com.sun.proxy.$Proxy254.getInstanceStatus(Unknown Source)
        at org.oscm.app.adapter.APPlatformControllerAdapter.getInstanceStatus(APPlatformControllerAdapter.java:67)
        at org.oscm.app.v2_0.service.APPTimerServiceBean.doHandleControllerProvisioning(APPTimerServiceBean.java:300)
        at org.oscm.app.v2_0.service.APPTimerServiceBean.doHandleSystems(APPTimerServiceBean.java:282)
        at org.oscm.app.v2_0.service.APPTimerServiceBean.handleTimer(APPTimerServiceBean.java:217)
        at sun.reflect.GeneratedMethodAccessor189.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
        at org.apache.openejb.monitoring.StatsInterceptor.record(StatsInterceptor.java:181)
        at org.apache.openejb.monitoring.StatsInterceptor.AroundTimeout(StatsInterceptor.java:145)
        at sun.reflect.GeneratedMethodAccessor166.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext$Invocation.invoke(ReflectionInvocationContext.java:205)
        at org.apache.openejb.core.interceptor.ReflectionInvocationContext.proceed(ReflectionInvocationContext.java:186)
        at org.apache.openejb.core.interceptor.InterceptorStack.invoke(InterceptorStack.java:85)
        at org.apache.openejb.core.singleton.SingletonContainer._invoke(SingletonContainer.java:272)
        at org.apache.openejb.core.singleton.SingletonContainer.invoke(SingletonContainer.java:221)
        at org.apache.openejb.core.timer.EjbTimerServiceImpl.ejbTimeout(EjbTimerServiceImpl.java:800)
        at org.apache.openejb.core.timer.EjbTimeoutJob.execute(EjbTimeoutJob.java:39)
        at org.apache.openejb.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by GoebelL** [comment]
@uhu133 
The load balancer is not available in current version. Target host and target storage have to be specified. 
Please report any issues for current version in https://github.com/servicecatalog/oscm/issues

**Comment by GoebelL** [comment]
This has been implemented with https://github.com/servicecatalog/oscm/issues/202
